# Generated by Django 5.1.3 on 2024-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='team',
            new_name='sexe',
        ),
        migrations.AddField(
            model_name='equipement',
            name='taille_max',
            field=models.IntegerField(default=1),
        ),
    ]
