# Generated by Django 5.1.3 on 2024-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_rename_team_character_sexe_equipement_taille_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
