# Generated by Django 5.1.3 on 2024-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_alter_equipement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
