# Generated by Django 5.1.3 on 2024-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_character_photo_alter_equipement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='puissance',
            field=models.IntegerField(default=20),
        ),
    ]
